package generator

import (
	"embed"
	"fmt"
	"os"
	"path/filepath"

	"github.com/dev-marees/goinit/internal/prompts"
)

var templates embed.FS

func createFiles(cfg prompts.Config) error {

	createGoMod(cfg)
	createEnv(cfg)
	createGitignore(cfg)
	createReadme(cfg)
	createMain(cfg)

	return nil
}

func createGoMod(cfg prompts.Config) {
	content := fmt.Sprintf(
		"module %s\n\ngo 1.25\n",
		cfg.ProjectName,
	)

	os.WriteFile(
		cfg.ProjectName+"/go.mod",
		[]byte(content),
		0644,
	)
}

func createEnv(cfg prompts.Config) {
	content := `APP_PORT=8080
APP_ENV=development
`

	os.WriteFile(
		cfg.ProjectName+"/.env",
		[]byte(content),
		0644,
	)
}

func createGitignore(cfg prompts.Config) {
	content := `
			.env
			bin/
			vendor/
			*.exe
			*.exe~
		`

	os.WriteFile(
		cfg.ProjectName+"/.gitignore",
		[]byte(content),
		0644,
	)
}

func createReadme(cfg prompts.Config) {
	content := fmt.Sprintf(
		"# %s\n\nGenerated by GoInit.\n",
		cfg.ProjectName,
	)

	os.WriteFile(
		cfg.ProjectName+"/README.md",
		[]byte(content),
		0644,
	)
}

func createMain(cfg prompts.Config) error {
	var templateFile string

	switch cfg.Framework {
	case "gin":
		templateFile = "templates/gin_main.go"
	case "fiber":
		templateFile = "templates/fiber_main.go"
	}

	content, err := templates.ReadFile(templateFile)
	if err != nil {
		return err
	}

	return os.WriteFile(
		filepath.Join(
			cfg.ProjectName,
			"cmd",
			"server",
			"main.go",
		),
		content,
		0644,
	)
}
